CC=g++
CXXFLAGS=-Wall -Wextra -O0 -g -pipe -I.. -I../SegmentIntersection

all: testSegmentIntersection

testSegmentIntersection: ../SegmentIntersection/Intersection.o ../SegmentIntersection/SegmentIntersection.o testSegmentIntersection.cpp
