CC=gcc
CFLAGS=-std=gnu99 -Wall -Wextra -O0 -g -pipe -I.. -I../SegmentIntersection

all: testSegmentIntersection

testSegmentIntersection: ../SegmentIntersection/SegmentIntersection.c testSegmentIntersection.c
